<?php

namespace Gina\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends EntityRepository
{

       public function findByVisiteur($user)
        {
          $qb= $this->createQueryBuilder('a')
                  ->select ('a')
                  ->where('a.visiteurs = :user')
                  ->setParameter('user ', $user);
          
          return $qb->getQuery()->getResult();
           
         }
    
}
