<?php

namespace Gina\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends EntityRepository
{
    
    public function findByMedias($media)
    {            
            $qb= $this->createQueryBuilder('p')
                  ->select ('p')
                  ->where('p.mediasPost= :id')
                  ->setParameter('id', $id);
          
          return $qb->getQuery()->getResult();
    }
            
}
