imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @GinaTestBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUserBundle Configuration
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: Gina\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
    group:
        group_class: Gina\UserBundle\Entity\Group 
    registration:
        form:
            type: gina_user_regismusiciens
    registration:
        form:
            type: gina_user_regisvisiteurs
        
 #JMSSecurityExtraBundle Configuration
jms_security_extra:
     secure_all_services: false
     expressions: true
     method_access_control: { }
 
 #SonataBlockBundle Configuration
sonata_block:
    default_contexts: [sonata_page_bundle]
    
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        sonata.media.block.media:
        sonata.media.block.gallery:
        #sonata.media.block.feature_media:
 
 #SonataAdminBundle Configuration           
sonata_admin:
    title:      Gina Test Bundle
    title_logo: Gina/TestBundle/Resources/images/play-button.png
    
    security:
        handler: sonata.admin.security.handler.role
        
    templates:
        dashboard:                SonataAdminBundle:Core:dashboard.html.twig
        search:                       SonataAdminBundle:Core:search.html.twig
        search_result_block:  SonataAdminBundle:Block:block_search_result.html.twig
        list:                       SonataAdminBundle:CRUD:list.html.twig
        action:                     SonataAdminBundle:CRUD:action.html.twig
        select:                     SonataAdminBundle:CRUD:list__select.html.twig
        list_block:                 SonataAdminBundle:Block:block_admin_list.html.twig
        short_object_description:   SonataAdminBundle:Helper:short-object-description.html.twig
        batch:                      SonataAdminBundle:CRUD:list__batch.html.twig
        inner_list_row:             SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:            SonataAdminBundle:CRUD:base_list_field.html.twig
        pager_links:                SonataAdminBundle:Pager:links.html.twig
        pager_results:              SonataAdminBundle:Pager:results.html.twig
        show:       GinaTestBundle:Admin:base_show.html.twig
            
            
    dashboard:          
                blocks:
            # display two dashboard blocks
                    -
                        position: left
                        type: sonata.admin.block.admin_list
                        settings:
                            groups: [sonata_page1]
                    -
                        position: right
                        type: sonata.admin.block.admin_list
                        settings:
                            groups: [sonata_page2]

                groups:
                    
                     gina.admin.group.content:
                        label: gina.admin.group.content
                        label_catalogue: GinaTestBundle
                        
                     sonata_page1:
                        items:
                            - sonata.admin.post
                            
                     sonata_page2:
#                         items:
#                            - sonata.admin.page
#                            - sonata.admin.page
                      
    options:
            use_select2:    true
 
#KnpMenuBundle Configuration            
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default




#pugx configuration
pugx_multi_user:
  users:
    musiciens:
        entity: 
          class: Gina\UserBundle\Entity\Musiciens
#          factory: 
        registration:
          form: 
            type: Gina\UserBundle\Form\RegisMusiciensFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: GinaUserBundle:Registration:musiciens.form.html.twig
        profile:
          form:
            type: Gina\UserBundle\Form\ProfileMusiciensFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default] 
    user_two:
        entity: 
          class: Gina\UserBundle\Entity\Visiteurs
        registration:
          form: 
            type: Gina\UserBundle\Form\RegisVisiteursFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: GinaUserBundle:Registration:visiteurs.form.html.twig
        profile:
          form: 
            type: Gina\UserBundle\Form\ProfileVisiteursFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default] 
